project:
  type: website

website:
  title: "Jack Rose"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jay-aye-see-kay/jackrose.co.nz
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



